name: tests

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: {
  contents: read
}

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  e2e:
    name: '✅ cypress'
    runs-on: ubuntu-latest
    steps:
      - name: '☁️ checkout repository'
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: '✅ Run Cypress'
        if: ${{ !env.ACT }}
        uses: cypress-io/github-action@v6

      - name: '☁️ Archive artifacts'
        uses: actions/upload-artifact@v5
        with:
          name: logs
          path: |
            logs
